## Numpy Array Operations

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing ", arr[2:7])
print("With Step", arr[1:10:2])
print("Negative indexing", arr[-3])

Basic Slicing  [3 4 5 6 7]
With Step [ 2  4  6  8 10]
Negative indexing 8


In [4]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]
                   ])
print("Specific element:", arr_2d[1, 2])
print("Entire Row: ", arr_2d[2])
print("Entire Column: ", arr_2d[:,1])

Specific element: 6
Entire Row:  [7 8 9]
Entire Column:  [2 5 8]


## Sorting

In [25]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 7])
print("Sorted Array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [4, 3]])
print("Sorted 2d array: ", np.sort(arr_2d_unsorted))
print("Sorted 2d array by column", np.sort(arr_2d_unsorted, axis=1))

Sorted Array:  [1 1 2 3 4 5 7 9]
Sorted 2d array:  [[1 3]
 [1 2]
 [3 4]]
Sorted 2d array by column [[1 3]
 [1 2]
 [3 4]]


## Filtering

In [16]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even Numbers", even_number)

Even Numbers [ 2  4  6  8 10]


## Filter with mask

In [17]:
mask = numbers > 5
print("Greater than 5 ", numbers[mask])

Greater than 5  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [26]:

indices = [0, 2, 4]
print(numbers[indices])
print(numbers)

where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
[ 1  2  3  4  5  6  7  8  9 10]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [19]:
condition_array = np.where(numbers > 5, numbers * 6, numbers)
print(condition_array)

condition_array = np.where(numbers > 5, "true", "false")
print(condition_array)

[ 1  2  3  4  5 36 42 48 54 60]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


In [20]:
# if(numbers > 5){
#     numbers * 4
# } else{
#     numbers
# }
# print(numbers)

### addding and removing data


In [21]:
arr1 =  np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined_array = np.concatenate((arr1, arr2))
print(combined_array)

[1 2 3 4 5 6]


### array compatibility

In [28]:
a = np.array([1, 2, 3])
b = np.array([4, 5 ,6, 8])
c = np.array([7, 8, 9])
print("Compatibily shapes: ", a.shape == b.shape)

Compatibily shapes:  False


In [31]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])
# vstack adds row every time
with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("with new column", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
with new column [[1 2 7]
 [3 4 8]]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6])
deleted = np.delete(arr, 2)
print("Array after deletion: ",deleted)

Array after deletion:  [1 2 4 5 6]
