## Numpy array and basics
learn about numpy with chai aur code

In [1]:
import numpy as np

### creating array from list

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4,5,6]])
print("2D array: ", arr_2d)

1D array: [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs Numpy array 

In [3]:
py_list = [1, 2, 3]
print("Python List Multiplication ",py_list*2)

np_array = np.array([1, 2, 3])
print("Python array multiplication ", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ",time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ",time.time()-start)


Python List Multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.06904935836791992

 Numpy operation time:  0.007993936538696289


### creating array from scratch

In [4]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

ones = np.ones((2, 3))
print("one array: \n", ones)

full = np.full((2,3), 4)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array: \n", random)

sequence = np.arange(0, 10, 2)
print("sequence array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[4 4 4]
 [4 4 4]]
random array: 
 [[0.68936975 0.40652921 0.38880498]
 [0.40940874 0.9802756  0.71253923]]
sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [5]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]] 
                  ])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [6]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  int64


### Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original array ",arr)

reshaped_arr = arr.reshape((3, 4))
print("Reshaped array", reshaped_arr)

flattened = reshaped_arr.flatten()
print("\n Flattened array ", flattened)

# ravel(returns view, instead of copy)
raveled = reshaped_arr.ravel()
print("\n Ravelled array ", raveled)

# Transpose
transpose = reshaped_arr.T
print("\n Transpored array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Ravelled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpored array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
