In [7]:
import numpy as np 
y = np.array([[1,2,3],[4,5,6]])
shape = y.shape  # (2, 3)
print(shape)
print(type(y))

(2, 3)
<class 'numpy.ndarray'>


In [10]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([1,0,1])
c = A + B  # --> Each row of A adds B
print(c)
print(type(c))

[[2 2 4]
 [5 5 7]]
<class 'numpy.ndarray'>


In [11]:
import numpy as np

print(np.__version__) 

2.0.2


In [28]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr) 
print(arr.dtype)

[1 2 3 4 5]
int64


In [29]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [30]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [31]:
import numpy as np

# 1 batch, 2 time steps, 1 image per time step, 2x2 pixels
arr = np.array([[[[[11, 12],
                   [13, 14]]],
                 
                 [[[21, 22],
                   [23, 24]]]]])

print(arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)


[[[[[11 12]
    [13 14]]]


  [[[21 22]
    [23 24]]]]]
Shape: (1, 2, 1, 2, 2)
Number of dimensions: 5


In [32]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[1, -1]) 

2nd element on 1st row:  10


In [33]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2]) 

6


In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:]) 

[5 6 7]


In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[0:5:2]) 

[1 3 5]


In [36]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [37]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [40]:
import numpy as np

arr = np.array([11, 222, 3454, 4], dtype='i4')

print(arr)
print(arr.dtype) 

[  11  222 3454    4]
int32


In [44]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype) 
print(arr.dtype)

[ True  True  True]
bool
float64


In [45]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Integer array indexing 
indices = np.array([1, 3, 5])
print ("Integer array indexing:", arr[indices])

# boolean array indexing 
cond = arr > 0
print ("\nElements greater than 0:\n", arr[cond])

Integer array indexing: [20 40 60]

Elements greater than 0:
 [ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
# print(x)
print(y.base)

None
[1 2 3 4 5]
[1 2 3 4 5]


In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [51]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [52]:
import numpy as np

# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))

# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))

# square root of array values
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [57]:
import numpy as np

# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), 
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.1)]
           
# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
            np.sort(arr, order = 'name'))
            
print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']))


Array sorted by names:
 [(b'Aakash', 2009, 9.1) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9.1)]
